#!/bin/bash

# PixelStack Landing Page - Quick Commands

echo "🚀 PixelStack Landing Page Commands"
echo "===================================="
echo ""
echo "Available commands:"
echo ""
echo "1) npm run dev      - اجرای development server (http://localhost:3000)"
echo "2) npm run build    - بیلد برای production"
echo "3) npm run lint     - چک کردن کد"
echo ""
echo "📂 مسیرها:"
echo "  - Components: src/components/"
echo "  - Styles: src/app/globals.css"
echo "  - Config: tailwind.config.js"
echo ""
echo "🎨 فایل‌های مهم برای تغییر:"
echo "  - Hero Section: src/components/HeroSection.tsx"
echo "  - Features: src/components/FeaturesSection.tsx"
echo "  - Colors: tailwind.config.js (line 10-30)"
echo "  - Metadata: src/app/layout.tsx (line 5-40)"
echo ""
echo "📦 GitHub Pages Deployment:"
echo "  1. git add ."
echo "  2. git commit -m 'Update landing page'"
echo "  3. git push origin contrib/matinsanei-verify"
echo "  4. GitHub Actions will auto-deploy!"
echo ""
